# Generated by Django 5.2 on 2025-05-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_course_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institute',
            field=models.IntegerField(default=-1),
        ),
    ]
