# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/openedu.innovativecollections.com
cert = /etc/letsencrypt/live/openedu.innovativecollections.com/cert.pem
privkey = /etc/letsencrypt/live/openedu.innovativecollections.com/privkey.pem
chain = /etc/letsencrypt/live/openedu.innovativecollections.com/chain.pem
fullchain = /etc/letsencrypt/live/openedu.innovativecollections.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = c22d5077df98c3d36dba38e6bc13976b
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
openedu.innovativecollections.com = /var/www/certbot
