# Use official Python runtime as the base image
FROM python:3.12.10-slim

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies required by your app
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    redis-server \
    && rm -rf /var/lib/apt/lists/*

# Copy the current directory contents into the container
COPY . /app/

COPY wait-for-elasticsearch.sh ./wait-for-elasticsearch.sh


# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the necessary ports
EXPOSE 8000 8001

# Set environment variables
ENV DJANGO_SETTINGS_MODULE=gitlms.settings

# Run Daphne and Django
CMD ["daphne", "-u", "unix:/tmp/daphne.sock", "gitlms.asgi:application"]
