# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/www.openedu.innovativecollections.com
cert = /etc/letsencrypt/live/www.openedu.innovativecollections.com/cert.pem
privkey = /etc/letsencrypt/live/www.openedu.innovativecollections.com/privkey.pem
chain = /etc/letsencrypt/live/www.openedu.innovativecollections.com/chain.pem
fullchain = /etc/letsencrypt/live/www.openedu.innovativecollections.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 54c9b104f691756fddb8f4e44dd190e8
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
www.openedu.innovativecollections.com = /var/www/certbot
