# Generated by Django 5.2 on 2025-05-01 17:51

import django.db.models.deletion
import lms.contentUploadStratagy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_temp_note_faculty_temp_slide_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(default='images/Institute/default.jpg', null=True, upload_to='images/Institute/')),
                ('description', models.TextField(default='The Institute is dedicated to academic excellence and cutting-edge research, fostering a dynamic environment that encourages interdisciplinary learning, professional growth, and impactful innovation across various fields.', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.NoteUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.SlideUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='temp_note',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.TempNoteUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='temp_slide',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.TempSlideUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='temp_video',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.TempVideoUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.VideoUploadStrategy.get_upload_to),
        ),
        migrations.AddField(
            model_name='department',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='lms.institute'),
        ),
    ]
