# Generated by Django 5.2 on 2025-05-14 12:52

import lms.contentUploadStratagy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0050_alter_note_content_alter_slide_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='uploaded_by',
            field=models.CharField(max_length=301, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='uploaded_by',
            field=models.CharField(max_length=301, null=True),
        ),
        migrations.AddField(
            model_name='temp_note',
            name='uploaded_by',
            field=models.CharField(max_length=301, null=True),
        ),
        migrations.AddField(
            model_name='temp_slide',
            name='uploaded_by',
            field=models.CharField(max_length=301, null=True),
        ),
        migrations.AddField(
            model_name='temp_video',
            name='uploaded_by',
            field=models.CharField(max_length=301, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='uploaded_by',
            field=models.CharField(max_length=301, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(default='This course provides a comprehensive overview of essential topics, methodologies, and concepts. Further details will be provided.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(default='The Department fosters innovative research and interdisciplinary collaboration, focusing on conceptual exploration and advanced academic problem-solving techniques.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='position',
            field=models.CharField(default='Lecturer', max_length=30),
        ),
        migrations.AlterField(
            model_name='institute',
            name='description',
            field=models.TextField(default='The Institute is dedicated to academic excellence and cutting-edge research, fostering a dynamic environment that encourages interdisciplinary learning, professional growth, and impactful innovation across various fields.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.NoteUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.SlideUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='temp_note',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.TempNoteUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='temp_slide',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.TempSlideUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='temp_video',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.TempVideoUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.VideoUploadStrategy.get_upload_to),
        ),
    ]
