# Generated by Django 5.2 on 2025-05-14 13:37

import lms.contentUploadStratagy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0053_alter_note_content_alter_slide_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.NoteUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.SlideUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='temp_note',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.TempNoteUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='temp_slide',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.TempSlideUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='temp_video',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.TempVideoUploadStrategy.get_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.FileField(upload_to=lms.contentUploadStratagy.VideoUploadStrategy.get_upload_to),
        ),
    ]
